services:
  backend:
    security_opt:
      - "no-new-privileges:false"
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - backend:/app
  frontend:
    security_opt:
      - "no-new-privileges:false"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend:/app
    env_file:
      - ./frontend/.env
volumes:
  backend:
  frontend: